### ISSUE TITLE
Determine experience when actions are not found

### ISSUE THREAD

**Issue by jeremypress** [browserbase/stagehand#46]
Currently, `act` will prompt stagehand to search the current page for an action to take. If that action is not found, we simply return. We should either throw an error or return an object payload letting the developer (or agent) know what happened

**Comment by filip-michalsky** [comment]
this is a great observation. Paul mentioned a vision where stagehand will be a tool we can pass to an LLM to perform an action on the web. In that sense, we DO want to return success/ failure signal and a reason for the failure so that the agent/developer can heal their pipelines (either manually or agentically)

**Comment by filip-michalsky** [comment]
we will return a message whether action succeeded or failed.

https://github.com/browserbase/stagehand/pull/79

**Comment by filip-michalsky** [comment]
addressed above in merged PR - we return an object:

``` 
return {
        success: true,
        message: `Action completed successfully: ${steps}${response.step}`,
        action: action,
      };
```

or 

```
      return {
        success: false,
        message: `Error performing action: ${error.message}`,
        action: action,
      };
```

**Comment by filip-michalsky** [comment]
example:
https://github.com/browserbase/stagehand/blob/main/lib/index.ts#L603
